CREATE TABLE [dbo].[Packet]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Uid] UNIQUEIDENTIFIER NOT NULL, 
    [Name] NVARCHAR(50) NOT NULL CONSTRAINT CK_Packet_Name UNIQUE, 
    [LogoUrl] NVARCHAR(400) NOT NULL
)
